import { BugInput } from '../components/BugInput'
import { StatCard } from '../components/StatCard'
import { InvestigationTimeline } from '../components/InvestigationTimeline'
import { Hero3D } from '../components/Hero3D'
import type { useBugAnalysis } from '../hooks/useBugAnalysis'

type DashboardProps = { onOpenInvestigation: () => void; analysis: ReturnType<typeof useBugAnalysis> }

export function Dashboard({ onOpenInvestigation, analysis }: DashboardProps) {
  const submit = (bug: string) => { void analysis.analyzeBug(bug).then(onOpenInvestigation).catch(() => undefined) }
  return <div className="mx-auto max-w-7xl"><section className="command-hero"><div className="relative z-10 max-w-xl"><p className="eyebrow text-samsung-bright">Samsung systems / live command center</p><h1 className="mt-5 text-5xl font-semibold leading-[0.98] tracking-[-0.05em] text-white sm:text-7xl">See the impact<br /><span className="hero-gradient">before it ships.</span></h1><p className="mt-6 max-w-md text-base leading-7 text-slate-300">NEXUS maps change across Samsung&apos;s connected ecosystem so every engineering decision starts with clarity.</p><button className="hero-cta mt-8" type="button" onClick={() => submit('Bluetooth disconnects after the latest One UI update')} disabled={analysis.loading}>{analysis.loading ? 'Analyzing Samsung systems…' : 'Run Samsung Demo'} <span>↗</span></button><div className="mt-8 flex items-center gap-3 text-xs text-muted"><span className="status-pulse" />Monitoring Galaxy ecosystem · 03 repositories</div></div><Hero3D /><div className="hero-orbit-label hero-orbit-label-phone">GALAXY PHONE<br /><span>BLUETOOTH CORE</span></div><div className="hero-orbit-label hero-orbit-label-watch">GALAXY WATCH<br /><span>POWER MONITOR</span></div><div className="hero-orbit-label hero-orbit-label-hub">SMARTTHINGS<br /><span>AUTOMATION BRIDGE</span></div></section><div className="mt-8 grid gap-4 sm:grid-cols-3"><StatCard label="Open investigations" value={analysis.data ? '01' : '00'} detail={analysis.loading ? `${analysis.stage} in progress` : 'Live backend workflow'} /><StatCard label="Evidence indexed" value={analysis.data ? String(analysis.data.evidence_trail.length) : '—'} detail="From repository analysis" accent="text-white" /><StatCard label="Workflow" value={analysis.data ? 'Ready' : 'Idle'} detail="Planner → patch validation" accent="text-emerald-400" /></div><div className="mt-6 grid gap-6 lg:grid-cols-[1.35fr_1fr]"><BugInput onSubmit={submit} loading={analysis.loading} /><InvestigationTimeline /></div>{analysis.loading && <div className="mt-6 rounded-3xl border border-samsung/20 bg-samsung/[0.06] p-5 text-sm text-slate-300">Running <span className="font-semibold text-samsung">{analysis.stage}</span>… Sequential agent progress will appear here.</div>}{analysis.error && <div className="mt-6 rounded-3xl border border-rose-400/20 bg-rose-400/[0.06] p-5 text-sm text-rose-200"><p>{analysis.error.error}</p><p className="mt-2 text-xs">{analysis.error.next_step}</p></div>}</div>
}
