import { BugInput } from '../components/BugInput'
import { StatCard } from '../components/StatCard'
import { InvestigationTimeline } from '../components/InvestigationTimeline'

type DashboardProps = { onOpenInvestigation: () => void }

export function Dashboard({ onOpenInvestigation }: DashboardProps) {
  return <div className="mx-auto max-w-6xl"><header className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Good evening, engineer</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Impact intelligence, <span className="text-samsung">simplified.</span></h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted">Understand change impact across your systems with a calm, focused workspace.</p></div><button className="self-start rounded-xl border border-white/10 px-4 py-2.5 text-sm text-muted transition hover:border-samsung/50 hover:text-white sm:self-auto">⌘ Settings</button></header><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Open investigations" value="04" detail="No API connection yet" /><StatCard label="Evidence indexed" value="—" detail="Available in the next phase" accent="text-white" /><StatCard label="System health" value="Ready" detail="Frontend foundation online" accent="text-emerald-400" /></div><div className="mt-6 grid gap-6 lg:grid-cols-[1.35fr_1fr]"><BugInput onSubmit={onOpenInvestigation} /><InvestigationTimeline /></div><div className="mt-6 rounded-3xl border border-samsung/20 bg-samsung/[0.06] p-5 sm:p-6"><p className="eyebrow text-samsung">Phase 6A foundation</p><div className="mt-2 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><p className="max-w-2xl text-sm leading-6 text-slate-300">The investigation workspace is ready for API-powered intelligence in the next phase.</p><button className="text-left text-sm font-semibold text-samsung hover:text-samsung-bright" onClick={onOpenInvestigation}>Preview workspace →</button></div></div></div>
}
